CREATE DATABASE `woodfurniture`;
USE `woodfurniture`;

create table users (
    id int generated by default as identity primary key,
    username varchar(50),
    email varchar(100),
    password varchar(1000),
    role varchar(20) default 'user' CHECK(role in ('user', 'admin'))
);
